# Generated by Django 5.2.9 on 2025-12-26 15:04
# Custom migration to fix availability_id column to allow NULL
# (SQLite doesn't support ALTER COLUMN, so we need to recreate the table)

from django.db import migrations


def forwards(apps, schema_editor):
    """Recreate the LinkReport table with proper NULL constraint on availability_id."""
    if schema_editor.connection.vendor != 'sqlite':
        # For other databases, just alter the column
        schema_editor.execute(
            "ALTER TABLE submissions_linkreport ALTER COLUMN availability_id DROP NOT NULL"
        )
        return

    # SQLite requires table recreation to change column constraints
    # Note: Using users_user (not users_customuser) as that's the actual table name
    schema_editor.execute("""
        CREATE TABLE submissions_linkreport_new (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            reason varchar(20) NOT NULL,
            details TEXT NOT NULL,
            status varchar(20) NOT NULL,
            resolution_notes TEXT NOT NULL,
            resolved_at datetime NULL,
            created_at datetime NOT NULL,
            availability_id bigint NULL,
            reported_by_id bigint NOT NULL,
            resolved_by_id bigint NULL
        );
    """)

    schema_editor.execute("""
        INSERT INTO submissions_linkreport_new
        SELECT id, reason, details, status, resolution_notes, resolved_at, created_at,
               availability_id, reported_by_id, resolved_by_id
        FROM submissions_linkreport;
    """)

    schema_editor.execute("DROP TABLE submissions_linkreport;")
    schema_editor.execute("ALTER TABLE submissions_linkreport_new RENAME TO submissions_linkreport;")

    # Recreate indexes
    schema_editor.execute(
        "CREATE INDEX submissions_linkreport_availability_id ON submissions_linkreport(availability_id);"
    )
    schema_editor.execute(
        "CREATE INDEX submissions_linkreport_reported_by_id ON submissions_linkreport(reported_by_id);"
    )
    schema_editor.execute(
        "CREATE INDEX submissions_linkreport_resolved_by_id ON submissions_linkreport(resolved_by_id);"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_linkreport_linksuggestion'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
