# Generated by Django 5.2.9 on 2025-12-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_fix_linkreport_availability_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkreport',
            name='documentary_slug',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='linkreport',
            name='documentary_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='linkreport',
            name='platform_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
