# Generated by Django 5.2.9 on 2025-12-23 07:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='people/')),
                ('bio', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='platforms/')),
                ('website', models.URLField(blank=True)),
                ('is_free', models.BooleanField(default=False, help_text='Is this a free platform?')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Documentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)])),
                ('synopsis', models.TextField()),
                ('poster', models.ImageField(blank=True, upload_to='posters/')),
                ('backdrop', models.ImageField(blank=True, upload_to='backdrops/')),
                ('trailer_url', models.URLField(blank=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20)),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('tmdb_id', models.CharField(blank=True, max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('directors', models.ManyToManyField(blank=True, related_name='directed', to='documentaries.person')),
                ('regions', models.ManyToManyField(blank=True, related_name='documentaries', to='documentaries.region')),
                ('sports', models.ManyToManyField(blank=True, related_name='documentaries', to='documentaries.sport')),
                ('themes', models.ManyToManyField(blank=True, related_name='documentaries', to='documentaries.theme')),
            ],
            options={
                'verbose_name_plural': 'documentaries',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('is_free', models.BooleanField(default=False)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_until', models.DateField(blank=True, null=True)),
                ('country_codes', models.JSONField(blank=True, default=list, help_text="List of country codes where available, e.g. ['FR', 'BE', 'CH']")),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('documentary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='documentaries.documentary')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='documentaries.platform')),
            ],
            options={
                'verbose_name_plural': 'availabilities',
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('documentary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_watchlists', to='documentaries.documentary')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
    ]
