# Generated by Django 5.2.9 on 2025-12-23 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('documentary', 'platform')},
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'documentary')},
        ),
    ]
