# Generated by Django 5.2.9 on 2025-12-23 14:12

from django.db import migrations, models


def detect_language_and_migrate(apps, schema_editor):
    """
    Detect language of existing synopses and migrate to the appropriate field.
    Uses simple heuristics: French articles/words indicate French.
    """
    Documentary = apps.get_model('documentaries', 'Documentary')

    # French indicators (common French words/patterns)
    french_indicators = [
        ' le ', ' la ', ' les ', ' un ', ' une ', ' des ', ' du ', ' de la ',
        ' et ', ' ou ', ' avec ', ' dans ', ' pour ', ' sur ', ' par ',
        ' ce ', ' cette ', ' ces ', ' son ', ' sa ', ' ses ',
        ' qui ', ' que ', ' dont ', ' où ',
        ' est ', ' sont ', ' été ', ' être ',
        ' au ', ' aux ', ' en ',
        "l'", "d'", "n'", "s'", "qu'",
        ' à ', ' ça ', ' très ', ' plus ', ' moins ',
    ]

    for doc in Documentary.objects.all():
        synopsis = doc.synopsis or ""
        synopsis_lower = synopsis.lower()

        # Count French indicators
        french_score = sum(1 for indicator in french_indicators if indicator in synopsis_lower)

        # If we find 2+ French indicators, it's likely French
        if french_score >= 2:
            doc.synopsis_fr = synopsis
            doc.synopsis_en = ""
        else:
            doc.synopsis_en = synopsis
            doc.synopsis_fr = ""

        doc.save()


def reverse_migration(apps, schema_editor):
    """Reverse: copy synopsis_en or synopsis_fr back to synopsis."""
    Documentary = apps.get_model('documentaries', 'Documentary')

    for doc in Documentary.objects.all():
        # Prefer English, fallback to French
        doc.synopsis = doc.synopsis_en or doc.synopsis_fr or ""
        doc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('documentaries', '0002_initial'),
    ]

    operations = [
        # Step 1: Add new fields first (keeping old synopsis)
        migrations.AddField(
            model_name='documentary',
            name='synopsis_en',
            field=models.TextField(blank=True, verbose_name='Synopsis (English)'),
        ),
        migrations.AddField(
            model_name='documentary',
            name='synopsis_fr',
            field=models.TextField(blank=True, verbose_name='Synopsis (French)'),
        ),
        # Step 2: Migrate data with language detection
        migrations.RunPython(detect_language_and_migrate, reverse_migration),
        # Step 3: Remove old field
        migrations.RemoveField(
            model_name='documentary',
            name='synopsis',
        ),
    ]
