# Generated by Django 5.2.9 on 2025-12-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('submission_pending', 'Submission Pending'), ('link_suggestion_pending', 'Link Suggestion Pending'), ('link_report_pending', 'Link Report Pending'), ('submission_approved', 'Submission Approved'), ('submission_rejected', 'Submission Rejected'), ('link_suggestion_approved', 'Link Suggestion Approved'), ('link_suggestion_rejected', 'Link Suggestion Rejected'), ('link_report_fixed', 'Link Report Fixed'), ('link_report_dismissed', 'Link Report Dismissed')], max_length=30),
        ),
    ]
