# Generated by Django 5.2.9 on 2025-12-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='documentary_poster',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='documentary_slug',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='documentary_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
