# Generated by Django 5.2.9 on 2025-12-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_add_documentary_denormalized_fields'),
    ]

    operations = [
    ]
